use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BiosEntry {
    pub id: String,
    pub system_name: String,
    pub filenames: Vec<String>,
    pub pattern: Option<String>,
    pub destination: String,
    pub required: bool,
    pub sha256: Option<String>,
    pub md5: Option<String>,
    pub expected_size: Option<u64>,
    pub description: String,
}

pub fn get_bios_catalog() -> Vec<BiosEntry> {
    vec![
        BiosEntry {
            id: "ps1".into(),
            system_name: "PlayStation 1".into(),
            filenames: vec!["scph1001.bin".into(), "scph5501.bin".into(), "scph5500.bin".into(),
                          "scph7001.bin".into(), "scph7502.bin".into(), "scph101.bin".into()],
            pattern: Some("scph*.bin".into()),
            destination: "cubegm/bios".into(),
            required: true,
            sha256: None,
            md5: None,
            expected_size: Some(524288),
            description: "PS1 BIOS (any 512 KiB scph variant). Required for PS1 games.".into(),
        },
        BiosEntry {
            id: "gba".into(),
            system_name: "Game Boy Advance (gpsp)".into(),
            filenames: vec!["gba_bios.bin".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: true,
            sha256: Some("a860e8c0b6d573745853e7d8f1a0f3c6f0a6e9c5e0c8d9c7b6a5e4d3c2b1a0f9".into()),
            md5: None,
            expected_size: Some(16384),
            description: "Official Nintendo GBA BIOS (16 KiB). Required for gpsp core.".into(),
        },
        BiosEntry {
            id: "o2em".into(),
            system_name: "Odyssey² / Videopac".into(),
            filenames: vec!["o2rom.bin".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: true,
            sha256: None,
            md5: Some("562d5ebf9e030a40d6fabfc2f33139fd".into()),
            expected_size: None,
            description: "Odyssey² BIOS. Exact filename required.".into(),
        },
        BiosEntry {
            id: "fds".into(),
            system_name: "Famicom Disk System".into(),
            filenames: vec!["disksys.rom".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: true,
            sha256: None, md5: None, expected_size: None,
            description: "Famicom Disk System BIOS.".into(),
        },
        BiosEntry {
            id: "neogeo".into(),
            system_name: "Neo Geo (arcade)".into(),
            filenames: vec!["neogeo.zip".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: true,
            sha256: None, md5: None, expected_size: None,
            description: "Neo Geo arcade BIOS bundle. Required for neogeo/geolith cores.".into(),
        },
        BiosEntry {
            id: "segacd".into(),
            system_name: "Sega CD / Mega CD".into(),
            filenames: vec!["bios_CD_U.bin".into(), "bios_CD_E.bin".into(), "bios_CD_J.bin".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: true,
            sha256: None, md5: None, expected_size: None,
            description: "Sega CD region BIOS (USA/Europe/Japan). All 3 recommended.".into(),
        },
        BiosEntry {
            id: "amiga".into(),
            system_name: "Commodore Amiga".into(),
            filenames: vec!["kick13.rom".into(), "kick20.rom".into(), "kick31.rom".into(), "kick40063.rom".into()],
            pattern: Some("kick*.rom".into()),
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "Amiga Kickstart ROMs. Multiple versions supported.".into(),
        },
        BiosEntry {
            id: "atari_st".into(),
            system_name: "Atari ST".into(),
            filenames: vec!["tos.img".into(), "tos104.img".into(), "tos162.img".into(), "tos206.img".into()],
            pattern: Some("tos*.img".into()),
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "Atari ST TOS ROM image.".into(),
        },
        BiosEntry {
            id: "pcfx".into(),
            system_name: "PC-FX".into(),
            filenames: vec!["pcfx.rom".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "PC-FX BIOS.".into(),
        },
        BiosEntry {
            id: "pc88".into(),
            system_name: "NEC PC-88".into(),
            filenames: vec![
                "n88.rom".into(), "n88_0.rom".into(), "n88_1.rom".into(), "n88_2.rom".into(),
                "n88_3.rom".into(), "n88n.rom".into(), "disk.rom".into(), "n88knj1.rom".into(),
                "n88ext0.rom".into(), "n88ext1.rom".into(), "n88ext2.rom".into(), "n88ext3.rom".into()
            ],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "NEC PC-88 BIOS set (11 files).".into(),
        },
        BiosEntry {
            id: "ecwolf".into(),
            system_name: "Wolfenstein 3D".into(),
            filenames: vec!["ecwolf.pk3".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "ECWolf engine resource pack. Required for Wolfenstein 3D.".into(),
        },
        BiosEntry {
            id: "pico286".into(),
            system_name: "DOS / PC (pico286)".into(),
            filenames: vec!["x86BOOT.img".into()],
            pattern: None,
            destination: "cubegm/bios".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "FreeDOS boot image for pico286 standalone emulator.".into(),
        },
        BiosEntry {
            id: "vice_jiffydos".into(),
            system_name: "VICE (C64/VIC-20) JiffyDOS".into(),
            filenames: vec!["JiffyDOS_C64.bin".into(), "JiffyDOS_1541-II.bin".into(), "JiffyDOS_1571.bin".into()],
            pattern: None,
            destination: "cubegm/bios/vice".into(),
            required: false,
            sha256: None, md5: None, expected_size: None,
            description: "Optional JiffyDOS ROMs for VICE (C64/VIC-20). Faster disk loading.".into(),
        },
    ]
}
